config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   get "mancity/kdb", to: "mancity#kdb", as: 'kdb'
   get "mancity/aguero", to: "mancity#aguero", as: 'aguero'
   get "mancity/kompany", to: "mancity#kompany", as: 'kompany'
   get "mancity/ederson", to: "mancity#ederson", as: 'ederson'
   get "mancity", to: "mancity#all_mancity", as: 'all_mancity'

   get "arsenal/monreal", to: "arsenal#monreal", as:'monreal'
   get "arsenal/wilshere", to: "arsenal#wilshere", as:'wilshere'
   get "arsenal/aubameyang", to: "arsenal#aubameyang", as:'aubameyang'
   get "arsenal/lacazette", to: "arsenal#lacazette", as:'lacazette'
   get "arsenal", to: "arsenal#all_arsenal", as: 'all_arsenal'

   get "realmadrid/ronaldo", to: "realmadrid#ronaldo" ,as:'ronaldo'
   get "realmadrid/ramos", to: "realmadrid#ramos", as:'ramos'
   get "realmadrid/modric", to: "realmadrid#modric", as:'modric'
   get "realmadrid/kroos", to: "realmadrid#kroos", as:'kroos'
   get "realmadrid", to: "realmadrid#all_realmadrid", as: 'all_realmadrid'

   get "barcelona/messi", to: "barcelona#messi", as:'messi'
   get "barcelona/iniesta", to: "barcelona#iniesta", as:'iniesta'
   get "barcelona/pique", to: "barcelona#pique", as:'pique'
   get "barcelona/suarez", to: "barcelona#suarez", as:'suarez'
   get "barcelona", to: "barcelona#all_barcelona", as: 'all_barcelona'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/arsenal_controller.rb
class ArsenalController < ApplicationController
  def monreal
  end

  def wilshere
  end

  def aubameyang
  end

  def lacazette
  end

end

app/controllers/barcelona_controller.rb
class BarcelonaController < ApplicationController
  def messi
  end

  def iniesta
  end

  def pique
  end

  def suarez
  end
end

app/controllers/mancity_controller.rb
class MancityController < ApplicationController
  def kdb
  end

  def aguero
  end

  def kompany
  end

  def ederson
  end

  def all
  end
end

app/controllers/realmadrid_controller.rb
class RealmadridController < ApplicationController
  def ronaldo
  end

  def ramos
  end

  def modric
  end

  def kroos
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/arsenal_helper.rb
module ArsenalHelper
end

app/helpers/barcelona_helper.rb
module BarcelonaHelper
end

app/helpers/mancity_helper.rb
module MancityHelper
end

app/helpers/realmadrid_helper.rb
module RealmadridHelper
end

app/views/arsenal/all_arsenal.html.erb
<h1>All Arsenal Players</h1>
<hr>
<ul>
  <h3>Players</h3>
  <li><%= link_to "Go To Monreal Page", monreal_path %></li>
  <li><%= link_to "Go To Wilshere Page", wilshere_path %> </li>
  <li><%= link_to "Go To Aubameyang Page", aubameyang_path %></li>
  <li><%= link_to "Go To Lacazette Page", lacazette_path %></li>
</ul>

<ul>
  <h3>Other Teams</h3>
  <li><%= link_to "Go To Real Madrid Page", all_realmadrid_path %></li>
  <li><%= link_to "Go To Barcelona Page", all_barcelona_path %></li>
  <li><%= link_to "Go To Man City Page", all_mancity_path %></li>
</ul>

app/views/arsenal/aubameyang.html.erb
<h1>Pierre-Emerick Aubameyang</h1>
<h3>Arsenal Striker</h3>
<hr>
<%= link_to "Go To Home Page", all_arsenal_path %>

app/views/arsenal/lacazette.html.erb
<h1>Alexander Lacazette</h1>
<h3>Arsenal Striker</h3>
<hr>
<%= link_to "Go To Home Page", all_arsenal_path %>

app/views/arsenal/monreal.html.erb
<h1>Nacho Monreal</h1>
<h3>Arsenal Left-Back</h3>
<hr>
<%= link_to "Go To Home Page", all_arsenal_path %>

app/views/arsenal/wilshere.html.erb
<h1>Jack Wilshere</h1>
<h3>Arsenal Midfielder</h3>
<hr>
<%= link_to "Go To Home Page", all_arsenal_path %>

app/views/barcelona/all_barcelona.html.erb
<h1>All Barcelona Players</h1>
<hr>
<ul>
  <h3>Players</h3>
  <li><%= link_to "Go To Messi Page", messi_path %></li>
  <li><%= link_to "Go To Iniesta Page", iniesta_path %> </li>
  <li><%= link_to "Go To Pique Page", pique_path %></li>
  <li><%= link_to "Go To Suarez Page", suarez_path %></li>
</ul>

<ul>
  <h3>Other Teams</h3>
  <li><%= link_to "Go To Real Madrid Page", all_realmadrid_path %></li>
  <li><%= link_to "Go To Man City Page", all_mancity_path %></li>
  <li><%= link_to "Go To Arsenal Page", all_arsenal_path %></li>
</ul>

app/views/barcelona/iniesta.html.erb
<h1>Andres Iniesta</h1>
<h3>Barcelona Midfielder</h3>
<hr>
<%= link_to "Go To Home Page", all_barcelona_path %>

app/views/barcelona/messi.html.erb
<h1>Lionel Messi</h1>
<h3>Barcelona Attacking Midfielder</h3>
<hr>
<%= link_to "Go To Home Page", all_barcelona_path %>

app/views/barcelona/pique.html.erb
<h1>Gerard Pique</h1>
<h3>Barcelona Defender</h3>
<hr>
<%= link_to "Go To Home Page", all_barcelona_path %>

app/views/barcelona/suarez.html.erb
<h1>Luis Suarez</h1>
<h3>Barcelona Striker</h3>
<hr>
<%= link_to "Go To Home Page", all_barcelona_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ControllerHw</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mancity/aguero.html.erb
<h1>Sergio Aguero</h1>
<h3>Mancity Striker</h3>
<hr>
<%= link_to "Go To Home Page", all_mancity_path %>

app/views/mancity/all_mancity.html.erb
<h1>All Man City Players</h1>
<hr>
<ul>
  <h3>Players</h3>
  <li><%= link_to "Go To Aguero Page", aguero_path %></li>
  <li><%= link_to "Go To Kompany Page", kompany_path %> </li>
  <li><%= link_to "Go To Ederson Page", ederson_path %></li>
  <li><%= link_to "Go To Kevin DeBruyne Page", kdb_path %></li>
</ul>

<ul>
  <h3>Other Teams</h3>
  <li><%= link_to "Go To Real Madrid Page", all_realmadrid_path %></li>
  <li><%= link_to "Go To Barcelona Page", all_barcelona_path %></li>
  <li><%= link_to "Go To Arsenal Page", all_arsenal_path %></li>
</ul>

app/views/mancity/ederson.html.erb
<h1>Ederson</h1>
<h3>Mancity Goalkeeper</h3>
<hr>
<%= link_to "Go To Home Page", all_mancity_path %>

app/views/mancity/kdb.html.erb
<h1>Kevin DeBruyne</h1>
<h3>Mancity Midfielder</h3>
<hr>
<%= link_to "Go To Home Page", all_mancity_path %>

app/views/mancity/kompany.html.erb
<h1>Vincent Kompany</h1>
<h3>Mancity Defender</h3>
<hr>
<%= link_to "Go To Home Page", all_mancity_path %>

app/views/realmadrid/all_realmadrid.html.erb
<h1>All Real Madrid Players</h1>
<hr>
<ul>
  <h3>Players</h3>
  <li><%= link_to "Go To Ronaldo Page", ronaldo_path %></li>
  <li><%= link_to "Go To Kroos Page", kroos_path %> </li>
  <li><%= link_to "Go To Modric Page", modric_path %></li>
  <li><%= link_to "Go To Ramos Page", ramos_path %></li>
</ul>

<ul>
  <h3>Other Teams</h3>
  <li><%= link_to "Go To Man City Page", all_mancity_path %></li>
  <li><%= link_to "Go To Barcelona Page", all_barcelona_path %></li>
  <li><%= link_to "Go To Arsenal Page", all_arsenal_path %></li>
</ul>

app/views/realmadrid/kroos.html.erb
<h1>Toni Kroos</h1>
<h3>Real Madrid Midfielder</h3>
<hr>
<%= link_to "Go To Home Page", all_realmadrid_path %>

app/views/realmadrid/modric.html.erb
<h1>Luka Modric</h1>
<h3>Real Madrid Midfielder</h3>
<hr>
<%= link_to "Go To Home Page", all_realmadrid_path %>

app/views/realmadrid/ramos.html.erb
<h1>Sergio Ramos</h1>
<h3>Real Madrid Defender</h3>

<%= link_to "Go To Home Page", all_realmadrid_path %>

app/views/realmadrid/ronaldo.html.erb
<h1>Cristiano Ronaldo</h1>
<h3>Real Madrid Striker</h3>

<%= link_to "Go To Home Page", all_realmadrid_path %>